### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by pablofmorales** [mikestead/bitbucket-semver#2]
Hey guys, 

I cannot use this script because this error

```
Cannot read property 'filter' of undefined
```

I think is referring to this line

```
  do {
    res = await getTagsPage(start, 20, options);
    // filter out any tags which aren't semver
    const tags = res.values.filter(tag =>
      SEMVER_TAG_PATTERN.test(tag.displayId)

```

Cheers,

**Comment by mikestead** [comment]
Thanks @pablofmorales, I've just pushed `v1.2.1` which should address this.

To be honest I think that value should come back as an empty array so let me know if you run into any other issues.

**Comment by mikestead** [comment]
Interesting. Are you able to tell me which version of Bitbucket you're running so I can try to reproduce?

**Comment by pablofmorales** [comment]
I am using bitbucket cloud, 

regarding git version 2.15.2 (Apple Git-101.1)

**Comment by mikestead** [comment]
Ah that's the issue then. This tool only supports the self hosted [Bitbucket Server](https://www.atlassian.com/software/bitbucket/server) currently. The REST api's are a bit different between that product and the cloud offering unfortunately.
